# 检验 使用 jdk 还是 cglib
ond:
    pro: 111
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
    port: 8085
spring:
    application:
        name: parent-server
    #    aop:
#        proxy-target-class: false
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: jsy251361
        url: jdbc:mysql://localhost:3306/degree?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
        username: root
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    # redis setting
    data:
        redis:
            database: 1
            host: localhost
            port: 6379
            password: 123456
            jedis:
                pool:
                    max-active: 1000
                    max-wait: -1ms
                    max-idle: 50
                    min-idle: 1
    # cache setting
    cache:
      redis:
          time-to-live: 60000
redisson:
    singleserverconfig:
        address: "redis://${spring.data.redis.host}:${spring.data.redis.port}"
        password: ${spring.data.redis.password}
        database: ${spring.data.redis.database}