cod:
    test: 111
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
    port: 8085
    servlet:
        context-path: /degree
spring:
    #    aop:
#        proxy-target-class: false
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: jsy251361
        url: jdbc:mysql://localhost:3306/degree?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
        username: root
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    # redis setting
#    data:
#        redis:
#            host: localhost
#            port: 6379
    # cache setting
#    cache:
#      redis:
#          time-to-live: 60000
