server:
  port: 9091

spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: true
      routes:
        - id: parent-service
          uri: http://localhost:8085
          predicates:
            - Path=/parent-service/**
          filters:
            - StripPrefix=1
#logging:
#    file:
#        name: D:/log/gateway.log
#    level:
#        springfox: error
#        cn.edu.sgu.www.gateway: debug